---
- block:

  - name: Install NTP package
    dnf:
      name: ntp
      state: present

  - name: Copy NTP config file
    copy:
      src: ntp.conf
      dest: /etc/ntp.conf

  - name: Sync system clock with NTP pool
    command: ntpdate -b pool.ntp.org
    ignore_errors: yes # This will fail if the NTP port is already bound.

  - name: Start and enable the NTP service
    systemd:
      name: ntpd
      state: started
      enabled: yes

  become: yes
