---
- hosts: all
  roles:
  - machine
  - admin_tools

- hosts: ntp
  roles:
  - ntp

- hosts: hostmaster
  roles:
  - hostmaster

- hosts: dns_backend
  roles:
  - dns_backend

- hosts: auth_dns
  roles:
  - auth_dns
