---
- fail: msg="Variable '{{ item }}' is not defined"
  when: item not in hostvars[inventory_hostname]
  with_items:
  - domain
  - static_ip
  - trusted_cidrs
  - private_cidrs
  - other_nameserver_ips
  - soa_subdomain
  - nameservers
- block:
  - name: Install BIND packages
    dnf: name={{item}} state=present
    with_items:
    - bind
    - bind-utils
  - name: Create named directories.
    file:
      path: "{{ item.path }}"
      owner: named
      group: named
      mode: "{{ item.mode }}"
      state: directory
    with_items:
    - {path: "{{ data_directory }}", mode: u=rwx,g=rx,o=}
    - {path: "{{ runtime_directory }}", mode: u=rwx,g=rx,o=rx}
    - {path: "{{ config_directory }}", mode: u=rwx,g=rx,o=}
    - {path: "{{ config_directory }}/zones", mode: u=rwx,g=rx,o=rx}
  - name: Create named config files.
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: named
      group: named
      mode: u=rw,g=r,o=r
    with_items:
    - {src: named.conf, dest: /etc/named.conf}
    - {src: named.local.conf, dest: /etc/named.local.conf}
    - {src: db.domain, dest: "{{ config_directory }}/zones/db.{{ domain }}"}
  become: yes
