---
- block:

  - name: Set hostname
    hostname:
      name: "{{machine_hostname}}"

  - name: Set timezone
    timezone:
      name: "{{machine_timezone}}"

  - name: Install SELinux Python support
    dnf:
      name: libselinux-python
      state: present

  - name: Update vim-minimal package
    dnf:
      name: vim-minimal
      state: latest

  become: yes
