---
- block:

  - name: Set hostname
    hostname:
      name: "{{machine_hostname}}"

  - name: Set timezone
    timezone:
      name: "{{machine_timezone}}"

  - name: Install SELinux Python support
    dnf:
      name: libselinux-python
      state: present

  become: yes
